version: '3.8'

services:
  skeleton-app-postgres:
    image: 'postgres:13-alpine'
    command: postgres -c 'max_connections=1000'
    container_name: toptal-hackathon-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toptal-hackathon
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '8432:5432'
